package com.fluxpay.service;
import com.fluxpay.beans.*; import com.fluxpay.common.contracts.KycGate; import com.fluxpay.config.M3BusinessException; import com.fluxpay.dto.*; import com.fluxpay.repository.*; import java.math.*; import java.time.*; import java.util.*; import org.springframework.data.domain.*; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class PaymentService {
 private final PaymentRepository payments; private final RecipientRepository recipients; private final M3WalletPort wallets; private final KycGate kyc; private final Clock clock;
 public PaymentService(PaymentRepository payments,RecipientRepository recipients,M3WalletPort wallets,KycGate kyc,Clock clock){this.payments=payments;this.recipients=recipients;this.wallets=wallets;this.kyc=kyc;this.clock=clock;}
 @Transactional public PaymentResponse draft(UUID userId,DraftPaymentRequest request){if(request.sourceCurrency().equals(request.payoutCurrency()))throw invalid("INVALID_CORRIDOR","Source and payout currencies must differ.");Recipient r=recipients.lockOwned(request.recipientId(),userId).orElseThrow(()->notFound("RECIPIENT_NOT_FOUND","Recipient not found."));if(!r.eligible())throw invalid("RECIPIENT_UNAVAILABLE","Recipient is blocked or incomplete.");if(!r.currency().equals(request.payoutCurrency()))throw invalid("CURRENCY_MISMATCH","Payout currency must match the recipient.");if(!kyc.isVerified(userId))throw new M3BusinessException(HttpStatus.FORBIDDEN,"KYC_NOT_VERIFIED","KYC verification is required.");M3WalletSnapshot wallet=wallets.findOwned(userId,request.sourceWalletId()).orElseThrow(()->notFound("WALLET_NOT_FOUND","Wallet not found."));if(!wallet.customerEligible()||!wallet.currency().equals(request.sourceCurrency()))throw invalid("WALLET_UNAVAILABLE","Wallet is not eligible for this payment.");if(wallet.availableFunds().compareTo(request.sourceAmount())<0)throw invalid("INSUFFICIENT_FUNDS","Available funds are insufficient.");String snapshot="{\"name\":\""+escape(r.name())+"\",\"account\":\""+escape(r.account())+"\",\"bankName\":\""+escape(r.bankName())+"\",\"country\":\""+r.country()+"\",\"currency\":\""+r.currency()+"\"}";Payment p=new Payment(UUID.randomUUID(),userId,request.sourceWalletId(),r,request.sourceAmount().setScale(4,RoundingMode.UNNECESSARY),request.sourceCurrency(),request.payoutCurrency(),request.purpose(),request.preference(),snapshot,Instant.now(clock));return response(payments.save(p));}
 @Transactional public PaymentResponse cancel(UUID userId,UUID id){Payment p=payments.lockOwned(id,userId).orElseThrow(()->notFound("PAYMENT_NOT_FOUND","Payment not found."));if(p.status()==PaymentLifecycleStatus.CANCELLED)return response(p);if(p.status()!=PaymentLifecycleStatus.DRAFT&&p.status()!=PaymentLifecycleStatus.QUOTED)throw new M3BusinessException(HttpStatus.CONFLICT,"INVALID_PAYMENT_STATE","Only draft or quoted payments can be cancelled.");p.cancel(Instant.now(clock));return response(p);}
 @Transactional(readOnly=true) public PaymentPageResponse list(UUID userId,int page,int size){Page<Payment> result=payments.findBySenderIdAndFlowVersionOrderByCreatedAtDescIdDesc(userId,1,PageRequest.of(page,Math.min(Math.max(size,1),100)));return new PaymentPageResponse(result.getContent().stream().map(this::response).toList(),page,result.getSize(),result.getTotalElements());}
 @Transactional(readOnly=true) public PaymentResponse detail(UUID userId,UUID id){return response(payments.findByIdAndSenderId(id,userId).orElseThrow(()->notFound("PAYMENT_NOT_FOUND","Payment not found.")));}
 private PaymentResponse response(Payment p){return new PaymentResponse(p.id(),p.sourceWalletId(),p.recipientId(),p.sourceAmount(),p.sourceCurrency(),p.payoutCurrency(),p.status(),p.selectedQuoteId(),null,false);} private String escape(String s){return s.replace("\\","\\\\").replace("\"","\\\"");} private M3BusinessException invalid(String c,String m){return new M3BusinessException(HttpStatus.UNPROCESSABLE_ENTITY,c,m);} private M3BusinessException notFound(String c,String m){return new M3BusinessException(HttpStatus.NOT_FOUND,c,m);}
}
