BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE flyway_baseline_marker(id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, created_at TIMESTAMP DEFAULT SYSTIMESTAMP)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
