CREATE TABLE users(id RAW(16) DEFAULT SYS_GUID() PRIMARY KEY, email VARCHAR2(255) NOT NULL UNIQUE, password_hash VARCHAR2(255) NOT NULL, role VARCHAR2(50) DEFAULT ''USER'' NOT NULL, created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL);
CREATE TABLE user_roles(user_id RAW(16) NOT NULL REFERENCES users(id), role VARCHAR2(50) NOT NULL, PRIMARY KEY(user_id, role));
CREATE TABLE refresh_tokens(id RAW(16) DEFAULT SYS_GUID() PRIMARY KEY, user_id RAW(16) NOT NULL REFERENCES users(id), token_hash VARCHAR2(255) NOT NULL, expires_at TIMESTAMP NOT NULL);
