CREATE TABLE recipients(id RAW(16) DEFAULT SYS_GUID() PRIMARY KEY, user_id RAW(16) NOT NULL REFERENCES users(id), name VARCHAR2(255) NOT NULL, account_ref VARCHAR2(255) NOT NULL, created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL);
CREATE TABLE payments(id RAW(16) DEFAULT SYS_GUID() PRIMARY KEY, sender_wallet_id RAW(16) NOT NULL REFERENCES wallets(id), recipient_id RAW(16) NOT NULL REFERENCES recipients(id), amount NUMBER(19,4) NOT NULL, currency VARCHAR2(3) NOT NULL, status VARCHAR2(20) DEFAULT ''CREATED'' NOT NULL, created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL);
CREATE TABLE payout_routes(code VARCHAR2(50) PRIMARY KEY, name VARCHAR2(255) NOT NULL, created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL);
INSERT INTO payout_routes(code, name) VALUES (''SWIFT_STANDARD'', ''SWIFT Standard'');
INSERT INTO payout_routes(code, name) VALUES (''INSTANT_UPI'', ''Instant UPI'');
INSERT INTO payout_routes(code, name) VALUES (''LOW_COST_ACH'', ''Low-cost ACH'');
CREATE TABLE payout_attempts(id RAW(16) DEFAULT SYS_GUID() PRIMARY KEY, payment_id RAW(16) NOT NULL REFERENCES payments(id), route_code VARCHAR2(50) NOT NULL REFERENCES payout_routes(code), status VARCHAR2(20) DEFAULT ''PENDING'' NOT NULL, created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL);
