CREATE TABLE outbox_events(id RAW(16) DEFAULT SYS_GUID() PRIMARY KEY, topic VARCHAR2(255) NOT NULL, payload CLOB NOT NULL, created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL);
CREATE TABLE document_embeddings(id RAW(16) DEFAULT SYS_GUID() PRIMARY KEY, doc_ref VARCHAR2(255) NOT NULL, embedding VECTOR(1536,FLOAT32), created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL);
