-- V704__m5_rich_policy_corpus.sql (formerly V604; fresh-schema renumbering).
-- Member 5: expands the policy corpus seeded in V703 into a richly populated set
-- suitable for real Oracle AI Vector Search retrieval quality testing (as opposed to
-- the placeholder one-liners V603 used just to satisfy the FK/demo wiring).
--
-- Two things happen here:
--   1. The 5 policies seeded in V603 have their `content` UPDATEd to full-length,
--      multi-paragraph text (V603 itself is never edited -- it already ran).
--   2. 8 new policy documents are INSERTed, covering every Payment Passport reason code
--      (see ComplianceAssessmentService) plus general customer-support Q&A.
--
-- This migration intentionally does NOT insert policy_chunks or embeddings directly --
-- chunking and embedding are the job of PolicyIndexingService (POST /api/policies/{id}/index),
-- so that what is stored in Oracle always matches what TextChunker + the active
-- EmbeddingProvider actually produce. The stale one-chunk placeholder rows V603 inserted
-- for the 5 updated documents are deleted below so they do not linger with content that no
-- longer matches the parent document; re-run the index endpoint for all 13 documents after
-- this migration applies (see README-OLLAMA-M5.md for a one-line loop).

-- ---------------------------------------------------------------
-- 1. Richer content for the 5 policies seeded in V603
-- ---------------------------------------------------------------

DELETE FROM policy_chunks WHERE policy_document_id IN (
  HEXTORAW('00000000000000000000000000005E01'),
  HEXTORAW('00000000000000000000000000005E02'),
  HEXTORAW('00000000000000000000000000005E03'),
  HEXTORAW('00000000000000000000000000005E04'),
  HEXTORAW('00000000000000000000000000005E05')
);

-- Customer Identity Verification Policy (348 words)
UPDATE policy_documents SET content = 'All customers must complete identity verification (KYC) before any international withdrawal is permitted; wallet funding, currency conversion between the customer''s own wallets, and viewing the dashboard remain available before verification, but outbound international payments do not. Verification has two stages. Stage one, completed at registration, captures full name, date of birth, country of residence, and mobile number; the account sits in NOT_STARTED status. Stage two requires the customer to submit a government-issued identity document -- an accepted Passport, National ID, Driving Licence, or, for the India corridor, Aadhaar or PAN with a supporting proof of address -- plus the document number and expiry date; the application then moves to PENDING and is queued for admin review. An administrator checks that the document type is on the accepted list, the document has not expired, the document number is legible and plausible for its type, and the name and date of birth on the document are consistent with the profile. Approval moves the application to VERIFIED and unlocks Send Money; rejection moves it to REJECTED with a mandatory, specific reason (for example "document image too blurred to read" or "proof of address older than the permitted 90-day window"), and the customer may resubmit corrected documents immediately. Any payment whose sender is not currently VERIFIED is automatically classified HIGH risk by the Payment Passport rule engine with reason code KYC_UNVERIFIED, regardless of amount or recipient history, and is routed to UNDER_REVIEW rather than PROCESSING. This is a hard gate, not a scored factor: identity verification is the single non-negotiable prerequisite for moving money out of the platform. The suggested action recorded on the case is to hold the payment and request that the customer complete KYC verification before any further processing is attempted; compliance staff should not approve a KYC_UNVERIFIED case on the payment side -- the correct remediation is always to resolve the underlying KYC application first, then re-run the assessment once the customer is VERIFIED. Re-verification (rather than first-time verification) is covered separately in the Enhanced Due Diligence and KYC Re-verification Policy, including document-expiry triggers and dormant-account reactivation checks.'
WHERE id = HEXTORAW('00000000000000000000000000005E01');

-- New Recipient Review Policy (349 words)
UPDATE policy_documents SET content = 'The first payment a customer sends to any given recipient carries materially higher risk than a payment to a recipient the customer has successfully paid before, because a first-time beneficiary has not yet been proven to be who the customer believes it is. Typical failure modes include a typo or transposed digit in an account number that silently redirects funds to an unrelated account, a compromised customer session used by an attacker to add a beneficiary the real customer never intended to pay, and social engineering where a customer is persuaded to add a fraudulent "supplier" or "landlord" account. Because none of these patterns are visible from the payment amount alone, the platform treats recipient novelty as its own explicit signal. When the Payment Passport rule engine finds no prior COMPLETED payment from this sender to this recipient, it adds the reason code FIRST_TRANSFER_TO_RECIPIENT at MEDIUM severity. A closely related signal, RECIPIENT_RECENTLY_ADDED, fires independently when the recipient record itself was created less than twenty-four hours before the payment was submitted -- see the Transaction Velocity and Recipient Frequency Policy for that rule in detail. A payment can carry one, both, or neither of these reasons; two or more MEDIUM reasons together are sufficient to classify the case MEDIUM risk and route it to UNDER_REVIEW even when no single HIGH-severity rule fires. The required remediation is not to reject the payment outright but to confirm recipient bank details before payout: an administrator should verify, through a channel independent of the payment flow itself (for example a callback to the customer''s registered mobile number, never a number supplied in the payment notes), that the customer genuinely intends to pay this specific account, and that the account name is consistent with the stated recipient name where the corridor supports name-matching. Once a recipient has three or more completed payments with no disputes, the FIRST_TRANSFER_TO_RECIPIENT and RECIPIENT_RECENTLY_ADDED signals no longer apply to that pairing and the reason code RECIPIENT_KNOWN is used instead to record that the relationship is established; such cases are typically auto-eligible for release at LOW risk absent any other flag.'
WHERE id = HEXTORAW('00000000000000000000000000005E02');

-- High Value Payment Policy (306 words)
UPDATE policy_documents SET content = 'Payments above a configured value threshold receive additional scrutiny because larger transfers are disproportionately represented in money-laundering typologies such as structuring avoidance, trade-based laundering, and one-off large withdrawals following account takeover. The platform currently sets this threshold at a USD-equivalent of 1,000 (configurable via fluxpay.compliance-high-value-threshold-usd), converted using the fixed reference table maintained by the compliance module rather than a live FX call, since classification only needs to be approximately right, not to the cent. Any payment whose source amount, once converted to USD equivalent, exceeds this threshold receives the reason code AMOUNT_EXCEEDS_THRESHOLD at MEDIUM severity. A single AMOUNT_EXCEEDS_THRESHOLD flag on an otherwise clean, KYC-verified payment to a known recipient does not by itself force manual review -- MEDIUM risk requires at least two MEDIUM-severity reasons before a case is routed to UNDER_REVIEW rather than PROCESSING. It is the combination that matters: a high-value payment to a first-time recipient, or a high-value payment with a missing purpose description, is exactly the pattern this policy exists to catch. When a case does reach manual review carrying AMOUNT_EXCEEDS_THRESHOLD, the reviewing administrator should request confirmation of the source of funds in plain language appropriate to the customer''s profile (salary, business receipts, sale of an asset, savings) and confirm it is broadly consistent with the customer''s registered occupation and account history where that information is available; the platform does not require formal documentary evidence of funds for a prototype-scale demo threshold, but production deployments handling real money should require it above a materially higher limit. Thresholds are deliberately expressed in USD equivalent rather than per-currency so that customers cannot evade review simply by choosing to route the same economic value through EUR or INR instead. Administrators who believe the threshold is miscalibrated for a given customer segment should raise the change through configuration, not by manually overriding individual case decisions inconsistently.'
WHERE id = HEXTORAW('00000000000000000000000000005E03');

-- Payment Hold and Recovery Policy (338 words)
UPDATE policy_documents SET content = 'A payment can be held for two structurally different reasons and the recovery path differs for each. The first is a compliance hold: the Payment Passport rule engine classified the payment MEDIUM or HIGH risk and it is sitting in UNDER_REVIEW awaiting an administrator''s approve or reject decision. No payout attempt has been made yet, no provider has been contacted, and no wallet funds have moved beyond the initial hold on the source wallet''s available balance. Approval releases the payment to PROCESSING; rejection returns the held funds to the customer''s available balance and the payment moves to a terminal REJECTED state. The second is a payout failure: the payment already passed compliance review, reached PROCESSING, and a payout attempt was submitted to a simulated provider adapter (Standard Bank Rail, Instant Payout, or Local Partner), but that attempt came back FAILED -- for example a simulated provider timeout or a rejected destination account. The platform must never debit the customer twice for the same failed attempt, so a failed payout is recorded as its own payout_attempts row (never overwriting the original) and the customer is offered exactly three recovery options on the Payment Detail screen: retry the same route (appropriate for a transient failure), switch to a different active route excluding the one that just failed (appropriate when a specific provider corridor appears to be down), or request a full refund. A refund is implemented as a new, independent balanced ledger journal that credits the original source wallet for the full source amount -- it is a compensating entry, never a deletion or edit of the original debit, which preserves a complete and auditable transaction history. The payment then moves to the terminal REFUNDED status. Whichever path a customer takes, every state transition -- hold placed, attempt failed, retry submitted, route switched, refund issued -- is published as a timestamped event and rendered on the payment timeline so the customer always has a complete, chronological explanation of what happened to their money and why, without needing to contact support.'
WHERE id = HEXTORAW('00000000000000000000000000005E04');

-- Country Transfer Rules (302 words)
UPDATE policy_documents SET content = 'Transfers connected to a small set of destinations require mandatory manual compliance review before any funds are released, independent of the amount, the sender''s KYC status, or the recipient''s payment history. The current high-risk destination list is: North Korea (KP), Iran (IR), Syria (SY), Myanmar (MM), Russia (RU), and Belarus (BY). This list mirrors common international sanctions and high-risk jurisdiction designations used across the payments industry and is intentionally kept short and specific rather than broad, so that legitimate transfers to neighbouring or unrelated countries are never incorrectly held. Because the current payments schema does not yet persist a recipient destination-country column, the platform receives this signal as an explicit caller-supplied hint (highRiskDestination) at assessment time rather than as an automatic database lookup; once a destination-country field exists on the recipient record, this should become a direct lookup against the list above rather than a hint the caller must remember to supply. When the hint is present and true, the rule engine adds the reason code HIGH_RISK_DESTINATION at HIGH severity -- a single HIGH-severity reason is sufficient on its own to classify the whole case HIGH risk and route it to UNDER_REVIEW, the same treatment given to an unverified sender. The required remediation is to route the case to manual compliance review for destination screening: an administrator should confirm the recipient''s country against the customer-declared destination, check for any recipient or beneficiary-bank name matches against sanctions or watchlists, and document the decision reasoning in the case''s decision note regardless of whether the outcome is approval or rejection. Payments correctly identified as HIGH_RISK_DESTINATION should never be auto-approved, and the platform does not currently support any override that bypasses this review step -- if a destination is added to or removed from the high-risk list, that is a configuration change, not a per-case decision.'
WHERE id = HEXTORAW('00000000000000000000000000005E05');

COMMIT;

-- ---------------------------------------------------------------
-- 2. New policy documents -- 8 more, spanning all 5 allowed categories
--    (KYC, AML, PAYMENT_REVIEW, COUNTRY_RULE, SUPPORT) and every reason code
--    the rule engine can currently emit.
-- ---------------------------------------------------------------

-- Enhanced Due Diligence and KYC Re-verification Policy (KYC, 323 words)
INSERT INTO policy_documents (id, title, category, content, document_hash) VALUES
(HEXTORAW('00000000000000000000000000005F01'),
 'Enhanced Due Diligence and KYC Re-verification Policy', 'KYC',
 'Initial KYC verification establishes identity at a single point in time; it does not remain accurate forever. This policy defines when a previously VERIFIED customer must be asked to re-verify, and when a customer''s profile warrants Enhanced Due Diligence (EDD) beyond the standard identity check described in the Customer Identity Verification Policy. Re-verification is triggered by any of the following: the identity document on file has passed its recorded expiry date; the account has been dormant (no login and no payment activity) for more than twelve months and is now being used again, particularly for an international withdrawal; the customer''s registered country of residence changes; or an administrator identifies a material inconsistency between the customer''s stated profile and observed behaviour, such as payment volumes far exceeding what the declared occupation would typically support. A re-verification request does not revoke existing wallet balances or transaction history; it places a hold on new international withdrawals until refreshed documents are reviewed and approved, exactly as if the customer were newly PENDING. Enhanced Due Diligence applies a stricter standard to a smaller set of higher-risk profiles: customers whose payments have repeatedly triggered HIGH_RISK_DESTINATION, customers who have had a prior KYC rejection for suspected document fraud rather than an honest documentation gap, and customers who send a sustained pattern of payments each individually below the high-value threshold but collectively well above it to the same or related recipients (a structuring pattern). For an EDD profile, administrators should require a second independent document type in addition to the primary identity document, ask the customer directly about the purpose and frequency of their international transfers, and review the full payment history rather than the single payment under assessment. EDD status should be documented on the customer''s KYC record with a clear reason, and reviewed at least every six months for as long as it remains in effect; it is not intended to be permanent unless the underlying risk factor persists.',
 '238b3409321fd043d0467fc10a18cccd369e3557be8f63ebd0c56091c45c8492');

-- Anti-Money Laundering Transaction Monitoring Standard (AML, 718 words)
INSERT INTO policy_documents (id, title, category, content, document_hash) VALUES
(HEXTORAW('00000000000000000000000000005F02'),
 'Anti-Money Laundering Transaction Monitoring Standard', 'AML',
 TO_CLOB('This standard defines how the platform monitors payment activity for patterns consistent with money laundering, and how staff should investigate and document what they find. It applies in addition to, not instead of, the deterministic Payment Passport rules described elsewhere: the Passport rules are per-payment and fully explainable, while this standard covers patterns that only become visible when looking across multiple payments and multiple customers over time. Four monitoring scenarios are in scope. First, structuring: a customer sending several payments, each individually below the high-value review threshold, in a short window to the same or closely related recipients, where the combined value would clearly have triggered review as a single transaction. Second, rapid recipient cycling: a customer adding and using several new recipients in quick succession, especially when each recipient receives only one or two payments before being abandoned -- a pattern more consistent with mule-account testing than with genuine family or business relationships. Third, velocity spikes: a sudden, sustained increase in either payment frequency or payment value relative to a customer''s own established baseline, independent of any single payment crossing a fixed threshold. Fourth, inconsistent narrative: payment purposes that are present (so they do not trigger PAYMENT_PURPOSE_MISSING) but do not plausibly match the customer''s profile, the recipient relationship, or the transfer corridor -- for example repeated "gift" transfers of large, round-numbered amounts to a business-sounding recipient name. None of these four scenarios map to a single automatic reason code the way KYC_UNVERIFIED or AMOUNT_EXCEEDS_THRESHOLD do, because each requires looking at a customer''s history rather than one payment in isolation; they are intended to be surfaced through periodic review of the compliance case queue and payment history rather than blocked in real time. When a compliance officer identifies a pattern matching any of these scenarios, the required response is to escalate internally: open a case note (even if no single payment is currently UNDER_REVIEW), attach the supporting evidence -- a list of the specific payment IDs, dates, amounts, and recipients that form the pattern -- and record the investigation outcome, whether that is closing the concern as a false positive, placing a temporary hold on further payments from the customer pending clarification, or escalating further per internal governance procedures. Case documentation must always include enough detail that a second reviewer could reach the same conclusion without needing to re-run the entire investigation from scratch, and closed cases and their supporting evidence must be retained for audit purposes rather than deleted. ') ||
 TO_CLOB('Confidentiality applies throughout: the fact that a customer''s activity is under monitoring or investigation must never be disclosed to the customer, to the recipient, or to any party outside the compliance function. Escalation follows a fixed timeline once a pattern is identified. Within one business day of first detection, the compliance officer must open the case note described above and make an initial severity call -- routine, elevated, or urgent -- based on the value involved and how far the pattern has already progressed. Routine cases are reviewed and closed or escalated within five business days. Elevated cases, where the pattern strongly resembles a known typology such as structuring or rapid recipient cycling, require a decision within two business days and, if a hold is placed on further customer activity while the investigation continues, that hold must itself be logged as its own event with a clear reason so it is visible on the customer''s account history. Urgent cases, where there is a credible and immediate risk of funds leaving the platform through an account believed to be compromised, require an initial containment action -- typically a temporary hold on outbound payments from the affected account -- within the same business day the pattern is identified, with full investigation to follow. Every closed case, regardless of severity or outcome, feeds back into the monitoring standard itself: false positives should be used to refine detection thresholds over time so that the same benign pattern is not repeatedly re-flagged, and confirmed true positives should be reviewed periodically as a group to check whether the underlying rules need to be tightened, expanded to catch a related pattern, or ported into the deterministic Payment Passport rule engine as a new formal reason code once the pattern is well enough understood to express as a simple, explainable rule rather than a judgement call.'),
 'c9d3d1198135522c36e4df5da51b3ee62302f49081e3cba0df2ba0ffd9bc1057');

-- Sanctions and Politically Exposed Persons Screening Procedure (AML, 333 words)
INSERT INTO policy_documents (id, title, category, content, document_hash) VALUES
(HEXTORAW('00000000000000000000000000005F03'),
 'Sanctions and Politically Exposed Persons Screening Procedure', 'AML',
 'Every customer and every recipient is screened against applicable sanctions lists, politically exposed persons (PEP) lists, and adverse-media sources at two points: once when the party is first onboarded (a customer registering, or a recipient being added to an account), and again immediately before any payment naming that party is released for payout. Screening at payment time, not only at onboarding time, matters because sanctions and PEP lists change continuously; a recipient that screened clean when added six months ago is not guaranteed to still screen clean today. A screening match is not, by itself, proof of a true match -- common names produce a high rate of false positives against any sanctions or PEP list, and the review procedure exists precisely to separate genuine hits from coincidental name matches. When automated screening returns a potential match, the case must be reviewed by a compliance officer before the payment is released, comparing available secondary identifiers -- date of birth, nationality, address, and where available a document number -- between the platform''s record and the list entry. A match confirmed on secondary identifiers is treated as a true positive: the payment is blocked, not merely held, and escalated per internal governance procedures rather than resolved by a single reviewer. A match that fails to corroborate on any secondary identifier is documented as a false positive with the specific distinguishing detail recorded (for example, a different date of birth), and the payment proceeds through the remaining Payment Passport rules normally. PEP status carries a different consequence from a sanctions match: it does not block a payment outright, but it does require Enhanced Due Diligence for as long as the PEP relationship exists, per the Enhanced Due Diligence and KYC Re-verification Policy, including closer review of the source of funds for any payment above the standard high-value threshold. Screening records, whether resolved as true positive, false positive, or PEP-flagged, must be retained with their supporting evidence for the same audit period as other compliance case records.',
 '1d696a7700c0ae9b121396689fd926aa7f634dc0fb12f2403684b3f30eecfb33');

-- Payment Purpose and Source of Funds Policy (PAYMENT_REVIEW, 348 words)
INSERT INTO policy_documents (id, title, category, content, document_hash) VALUES
(HEXTORAW('00000000000000000000000000005F04'),
 'Payment Purpose and Source of Funds Policy', 'PAYMENT_REVIEW',
 'Every withdrawal must include a payment purpose description of at least ten characters that plausibly explains why the transfer is being made. Acceptable purpose categories mirrored in the product include family support, education, business payment, and savings or personal transfer, but the field accepts free text so a customer can be specific -- "tuition fee for spring semester" is both more useful to a reviewer and less likely to be flagged than a bare category label. A purpose field that is empty, or that is present but too short or generic to convey any real information (single words like "payment" or "transfer" with nothing else), is treated as functionally missing. When the payment purpose is missing or insufficient, the Payment Passport rule engine records the reason code PAYMENT_PURPOSE_MISSING at MEDIUM severity. On its own this does not force a case to UNDER_REVIEW -- as with other MEDIUM-severity signals, it takes at least two such reasons together, or one HIGH-severity reason, to route a payment to manual review -- but a missing purpose materially increases the chance that an otherwise-borderline payment (for example, one that is also a first transfer to a new recipient) tips into review. The required remediation when a case does reach review carrying this reason is straightforward: request that the customer provide a specific, plausible purpose before the payment proceeds. Reviewers should not invent or assume a purpose on the customer''s behalf. For payments that also exceed the high-value threshold, purpose alone is not sufficient; the reviewer should additionally confirm, in plain conversational terms appropriate to a prototype-scale review, that the stated source of funds (salary, business income, savings, proceeds of a sale) is broadly consistent with both the purpose given and the customer''s registered profile. A stated purpose that is internally inconsistent with the transfer pattern -- for instance, "family support" attached to a payment sent to a newly added recipient with a business-sounding name -- should be treated as a prompt for closer review under the Anti-Money Laundering Transaction Monitoring Standard, not accepted at face value simply because the purpose field is non-empty.',
 '36be9789fd62a7ff21fe6061ea573a39a1dc66cd24a7e0e030da6664b15c5dc4');

-- Transaction Velocity and Recipient Frequency Policy (PAYMENT_REVIEW, 323 words)
INSERT INTO policy_documents (id, title, category, content, document_hash) VALUES
(HEXTORAW('00000000000000000000000000005F05'),
 'Transaction Velocity and Recipient Frequency Policy', 'PAYMENT_REVIEW',
 'Two related but distinct signals govern how quickly a recipient or a payment pattern is treated as established rather than novel. The first, recipient recency, looks at a single recipient record: if a recipient was created less than twenty-four hours before the payment naming it was submitted, the Payment Passport rule engine adds the reason code RECIPIENT_RECENTLY_ADDED at MEDIUM severity. The rationale is that an attacker who has taken over a customer''s session typically adds a new beneficiary and attempts to move funds within minutes to hours, while a genuine new business or family relationship being set up by the real customer is not usually paid within the same day it is added. This signal is independent of, and commonly co-occurs with, FIRST_TRANSFER_TO_RECIPIENT (see the New Recipient Review Policy) -- a recipient can be both brand new and being paid for the first time, which is exactly the highest-risk combination this pair of rules is designed to catch together. The second signal, payment velocity, looks across a customer''s recent payment history as a whole rather than at one recipient: a sharp increase in the number of payments or the total value sent within a short rolling window, relative to that customer''s own established baseline, is a pattern more thoroughly covered in the Anti-Money Laundering Transaction Monitoring Standard, since it typically requires judgement across multiple payments rather than a single deterministic threshold. Where a genuine new relationship needs to be paid urgently -- a real emergency family transfer to a recipient added the same day, for example -- the correct response is not to bypass the rule but to complete the confirmation step quickly: an administrator verifies the recipient details through an independent channel, as described in the New Recipient Review Policy, and approves the case once satisfied. There is no cooling-off period hard-coded into the platform that blocks same-day payment to a new recipient outright; RECIPIENT_RECENTLY_ADDED is a review trigger, not a rejection.',
 '7574a9b365cd4e35e43ffbe9bc8452860affba4207bb95b73394e4441783948b');

-- Refund and Failed Payout Recovery Policy (SUPPORT, 381 words)
INSERT INTO policy_documents (id, title, category, content, document_hash) VALUES
(HEXTORAW('00000000000000000000000000005F06'),
 'Refund and Failed Payout Recovery Policy', 'SUPPORT',
 'This policy sets the operational standard for handling a failed payout attempt, expanding on the recovery mechanics summarised in the Payment Hold and Recovery Policy. When a payout provider adapter reports failure -- in the simulated environment, a deterministic failure such as a simulated provider timeout, or a destination account rejection from the Local Partner adapter above its configured amount limit -- the platform must guarantee three things: the customer is never charged twice for the same transfer, the failure and every subsequent recovery action is fully visible on the payment timeline, and the customer always has a clear, immediate choice of what happens next rather than an indefinite silent hold. The three recovery actions available from the Payment Detail screen are retry, switch route, and refund. Retry re-submits the same route as a new, separately numbered payout attempt -- appropriate when the failure looks transient, such as a timeout, rather than a structural rejection. Switch route selects a different currently active payout route, excluding the one that just failed, and generates its own new payout attempt with its own fee and ETA, which must be shown to the customer before they accept it, since the alternate route may cost more or take longer than the one originally quoted. Refund reverses the hold entirely: a new, independent balanced ledger journal credits the original source wallet the full source amount, the payment moves to the terminal REFUNDED status, and no further payout attempt is made. Refund is implemented as a compensating entry precisely because ledger entries are immutable and append-only throughout the platform -- the original debit is never edited or deleted, so the full history of what was attempted remains visible for audit. A refund request is idempotent: if a customer or an automated retry submits the same refund request twice for the same payment (for example due to a network retry on the client side), the platform must return the existing refund journal rather than creating a second one, preventing an accidental double credit. Administrators reviewing a FAILED payment that has sat without customer action for an extended period should proactively reach out rather than leaving the payment indefinitely unresolved, since from the customer''s perspective their money is currently in limbo until one of the three recovery actions is taken.',
 '98b505fb171670589e5e585c3726cb3c09b7e4f15c09d986d2ca037aa9987a59');

-- Customer Support FAQ: Wallets, Fees and Conversions (SUPPORT, 468 words)
INSERT INTO policy_documents (id, title, category, content, document_hash) VALUES
(HEXTORAW('00000000000000000000000000005F07'),
 'Customer Support FAQ: Wallets, Fees and Conversions', 'SUPPORT',
 'This FAQ answers the questions customers and support staff ask most often about everyday wallet use, as distinct from the compliance-focused policies elsewhere in this corpus. How do I check my balance? Open the Wallet Dashboard; each currency you hold (USD, EUR, INR) shows as its own card with available balance and any held balance shown separately -- held balance reflects funds currently locked against a payment that is mid-flight, such as one awaiting compliance review. How do I add money to my wallet for testing? Use the Receive Demo Money action on the dashboard; this is a simulated inbound credit for demo purposes only, it never touches a real bank. What does currency conversion cost? Converting between your own wallets (for example USD to INR) applies a demo conversion fee on top of the reference exchange rate; the exact fee percentage and the live rate are always shown in the conversion preview before you confirm, along with a timestamp for when the rate was fetched, so you know exactly what you are agreeing to before any balance moves. Where does the exchange rate come from? The platform calls a reference FX rate provider on the backend and caches the result for about an hour; this is a reference rate for demonstration purposes, not a guaranteed tradeable bank quote, and it can differ slightly from the rate you might see at an actual bank. How do I add a recipient, and why is mine shown as blocked? Add a recipient from the Recipients screen with their name, country, currency, and account details; a recipient can be set to BLOCKED status by an administrator or by the customer themselves if a mistake was made when adding it, and a blocked recipient cannot be selected when sending a new payment until it is re-activated or a corrected recipient is added. Why is my payment showing as under review instead of completed? See the Payment Passport on the Payment Detail screen -- it lists the specific, plain-language reasons the payment was flagged (for example, first transfer to this recipient, or KYC not yet verified) and the suggested next action; this is intentionally transparent rather than a generic "pending" status with no explanation. What do the KYC statuses mean? NOT_STARTED means no application has been submitted yet; PENDING means an application is submitted and awaiting admin review; VERIFIED unlocks international withdrawals; REJECTED means the submitted documents did not pass review, and the specific reason is always shown so you can correct and resubmit. Where can I see all my past transactions? The Transaction History screen lists all payments and, on a separate tab, the full wallet ledger showing every individual debit and credit -- ledger entries are never edited or deleted, only added to, so this is a complete and permanent record.',
 'ea787da94cfc3e65e024d05afaac464bf55bcad9cb2c88f26f27044800dfeecb');

-- KYC Document Types and Expiry Policy (KYC, 345 words)
INSERT INTO policy_documents (id, title, category, content, document_hash) VALUES
(HEXTORAW('00000000000000000000000000005F08'),
 'KYC Document Types and Expiry Policy', 'KYC',
 'This policy lists which identity documents are accepted for KYC verification, and the specific reasons a submitted document is rejected, expanding on the general verification process described in the Customer Identity Verification Policy. Accepted primary document types are: Passport (any issuing country), National ID card, and Driving Licence. For the India corridor specifically, Aadhaar or PAN may be used as the primary identity document, but must be accompanied by a separate proof-of-address document (a recent utility bill or bank statement) no older than ninety days, since Aadhaar and PAN alone do not reliably confirm current address. Exactly one document per accepted type may be attached to a given KYC application; submitting a second document of the same type replaces metadata for that type rather than creating a duplicate record. A submitted document is rejected, with the specific reason always recorded on the KYC application so the customer knows exactly what to fix, for any of the following: the document has already expired as of the submission date; the document image is too blurred, cropped, or low-resolution for the document number, name, or date of birth to be read with confidence; the name or date of birth on the document does not match the profile information entered at registration; the document type is not on the accepted list for the customer''s declared country; or, for the India corridor, the accompanying proof of address is older than the ninety-day window even though the primary Aadhaar or PAN document itself is valid. A rejection is never silent -- the rejection reason is a mandatory field on the admin review action, and an empty or placeholder reason is rejected by the platform itself before the KYC decision can be saved. Document expiry does not only matter at initial submission. Per the Enhanced Due Diligence and KYC Re-verification Policy, a previously VERIFIED customer whose document has since passed its recorded expiry date is required to submit a current document before further international withdrawals are permitted, even though their account was fully verified at the time the original document was accepted.',
 'e43465c6a1a437428fd8b4592ad56e3612d7e242fdc9bf226d4e88be19d4887d');

COMMIT;

-- Total corpus after this migration: 13 policy documents, ~4882 words of source
-- content across KYC, AML, PAYMENT_REVIEW, COUNTRY_RULE and SUPPORT. The AML transaction
-- monitoring standard alone is long enough (~700+ words) that TextChunker will split it into
-- 2 overlapping chunks when indexed, giving a realistic multi-chunk retrieval example; every
-- other document fits in a single chunk (<=700 words) as expected for a policy of this size.
